["lib/access.ex", "lib/agent.ex", "lib/agent/server.ex", "lib/application.ex",
 "lib/atom.ex", "lib/base.ex", "lib/behaviour.ex", "lib/bitwise.ex",
 "lib/calendar.ex", "lib/calendar/date.ex", "lib/calendar/date_range.ex",
 "lib/calendar/datetime.ex", "lib/calendar/iso.ex",
 "lib/calendar/naive_datetime.ex", "lib/calendar/time.ex",
 "lib/calendar/time_zone_database.ex", "lib/code.ex", "lib/code/formatter.ex",
 "lib/code/fragment.ex", "lib/code/identifier.ex", "lib/code/normalizer.ex",
 "lib/code/typespec.ex", "lib/collectable.ex", "lib/config.ex",
 "lib/config/provider.ex", "lib/config/reader.ex", "lib/dict.ex",
 "lib/dynamic_supervisor.ex", "lib/enum.ex", "lib/exception.ex", "lib/file.ex",
 "lib/file/stat.ex", "lib/file/stream.ex", "lib/float.ex", "lib/function.ex",
 "lib/gen_event.ex", "lib/gen_event/stream.ex", "lib/gen_server.ex",
 "lib/hash_dict.ex", "lib/hash_set.ex", "lib/inspect.ex",
 "lib/inspect/algebra.ex", "lib/integer.ex", "lib/io.ex", "lib/io/ansi.ex",
 "lib/io/ansi/docs.ex", "lib/io/stream.ex", "lib/kernel.ex",
 "lib/kernel/cli.ex", "lib/kernel/error_handler.ex",
 "lib/kernel/lexical_tracker.ex", "lib/kernel/parallel_compiler.ex",
 "lib/kernel/parallel_require.ex", "lib/kernel/special_forms.ex",
 "lib/kernel/typespec.ex", "lib/kernel/utils.ex", "lib/keyword.ex",
 "lib/list.ex", "lib/list/chars.ex", "lib/macro.ex", "lib/macro/env.ex",
 "lib/map.ex", "lib/map_set.ex", "lib/module.ex",
 "lib/module/locals_tracker.ex", "lib/module/parallel_checker.ex",
 "lib/module/types.ex", "lib/module/types/behaviour.ex",
 "lib/module/types/expr.ex", "lib/module/types/helpers.ex",
 "lib/module/types/of.ex", "lib/module/types/pattern.ex",
 "lib/module/types/unify.ex", "lib/node.ex", "lib/option_parser.ex",
 "lib/partition_supervisor.ex", "lib/path.ex", "lib/port.ex", "lib/process.ex",
 "lib/protocol.ex", "lib/range.ex", "lib/record.ex", "lib/record/extractor.ex",
 "lib/regex.ex", "lib/registry.ex", "lib/set.ex", "lib/stream.ex",
 "lib/stream/reducers.ex", "lib/string.ex", "lib/string/chars.ex",
 "lib/string_io.ex", "lib/supervisor.ex", "lib/supervisor/default.ex",
 "lib/supervisor/spec.ex", "lib/system.ex", "lib/task.ex",
 "lib/task/supervised.ex", "lib/task/supervisor.ex", "lib/tuple.ex",
 "lib/uri.ex", "lib/version.ex", "test/elixir/access_test.exs",
 "test/elixir/agent_test.exs", "test/elixir/application_test.exs",
 "test/elixir/atom_test.exs", "test/elixir/base_test.exs",
 "test/elixir/bitwise_test.exs", "test/elixir/calendar/date_range_test.exs",
 "test/elixir/calendar/date_test.exs", "test/elixir/calendar/datetime_test.exs",
 "test/elixir/calendar/fakes.exs", "test/elixir/calendar/holocene.exs",
 "test/elixir/calendar/iso_test.exs",
 "test/elixir/calendar/naive_datetime_test.exs",
 "test/elixir/calendar/time_test.exs", "test/elixir/calendar_test.exs",
 "test/elixir/changelog_test.exs", "test/elixir/code_formatter/calls_test.exs",
 "test/elixir/code_formatter/comments_test.exs",
 "test/elixir/code_formatter/containers_test.exs",
 "test/elixir/code_formatter/general_test.exs",
 "test/elixir/code_formatter/integration_test.exs",
 "test/elixir/code_formatter/literals_test.exs",
 "test/elixir/code_formatter/operators_test.exs",
 "test/elixir/code_fragment_test.exs", "test/elixir/code_identifier_test.exs",
 "test/elixir/code_normalizer/formatted_ast_test.exs",
 "test/elixir/code_normalizer/quoted_ast_test.exs", "test/elixir/code_test.exs",
 "test/elixir/collectable_test.exs", "test/elixir/config/provider_test.exs",
 "test/elixir/config/reader_test.exs", "test/elixir/config_test.exs",
 "test/elixir/dynamic_supervisor_test.exs", "test/elixir/enum_test.exs",
 "test/elixir/exception_test.exs", "test/elixir/file_test.exs",
 "test/elixir/fixtures/at_exit.exs", "test/elixir/fixtures/checker_warning.exs",
 "test/elixir/fixtures/code_sample.exs",
 "test/elixir/fixtures/compile_sample.ex",
 "test/elixir/fixtures/configs/bad_app.exs",
 "test/elixir/fixtures/configs/bad_import.exs",
 "test/elixir/fixtures/configs/env.exs",
 "test/elixir/fixtures/configs/good_config.exs",
 "test/elixir/fixtures/configs/good_import.exs",
 "test/elixir/fixtures/configs/good_kw.exs",
 "test/elixir/fixtures/configs/imports_recursive.exs",
 "test/elixir/fixtures/configs/kernel.exs",
 "test/elixir/fixtures/configs/nested.exs",
 "test/elixir/fixtures/configs/recursive.exs",
 "test/elixir/fixtures/consolidation/sample.ex",
 "test/elixir/fixtures/consolidation/with_any.ex",
 "test/elixir/fixtures/dialyzer/assertions.ex",
 "test/elixir/fixtures/dialyzer/boolean_check.ex",
 "test/elixir/fixtures/dialyzer/callback.ex",
 "test/elixir/fixtures/dialyzer/cond.ex",
 "test/elixir/fixtures/dialyzer/defmacrop.ex",
 "test/elixir/fixtures/dialyzer/for_bitstring.ex",
 "test/elixir/fixtures/dialyzer/for_boolean_check.ex",
 "test/elixir/fixtures/dialyzer/is_struct.ex",
 "test/elixir/fixtures/dialyzer/macrocallback.ex",
 "test/elixir/fixtures/dialyzer/protocol_opaque.ex",
 "test/elixir/fixtures/dialyzer/raise.ex",
 "test/elixir/fixtures/dialyzer/remote_call.ex",
 "test/elixir/fixtures/dialyzer/rewrite.ex",
 "test/elixir/fixtures/dialyzer/struct_update.ex",
 "test/elixir/fixtures/dialyzer/try.ex",
 "test/elixir/fixtures/dialyzer/with.ex", "test/elixir/float_test.exs",
 "test/elixir/function_test.exs", "test/elixir/gen_server_test.exs",
 "test/elixir/inspect/algebra_test.exs", "test/elixir/inspect_test.exs",
 "test/elixir/integer_test.exs", "test/elixir/io/ansi/docs_test.exs",
 "test/elixir/io/ansi_test.exs", "test/elixir/io_test.exs",
 "test/elixir/kernel/alias_test.exs", "test/elixir/kernel/binary_test.exs",
 "test/elixir/kernel/charlist_test.exs", "test/elixir/kernel/cli_test.exs",
 "test/elixir/kernel/comprehension_test.exs",
 "test/elixir/kernel/defaults_test.exs",
 "test/elixir/kernel/deprecated_test.exs",
 "test/elixir/kernel/dialyzer_test.exs", "test/elixir/kernel/docs_test.exs",
 "test/elixir/kernel/errors_test.exs", "test/elixir/kernel/expansion_test.exs",
 "test/elixir/kernel/fn_test.exs", "test/elixir/kernel/guard_test.exs",
 "test/elixir/kernel/impl_test.exs", "test/elixir/kernel/import_test.exs",
 "test/elixir/kernel/lexical_tracker_test.exs",
 "test/elixir/kernel/macros_test.exs",
 "test/elixir/kernel/overridable_test.exs",
 "test/elixir/kernel/parallel_compiler_test.exs",
 "test/elixir/kernel/parser_test.exs", "test/elixir/kernel/quote_test.exs",
 "test/elixir/kernel/raise_test.exs", "test/elixir/kernel/sigils_test.exs",
 "test/elixir/kernel/special_forms_test.exs",
 "test/elixir/kernel/string_tokenizer_test.exs",
 "test/elixir/kernel/tracers_test.exs", "test/elixir/kernel/warning_test.exs",
 "test/elixir/kernel/with_test.exs", "test/elixir/kernel_test.exs",
 "test/elixir/keyword_test.exs", "test/elixir/list/chars_test.exs",
 "test/elixir/list_test.exs", "test/elixir/macro_test.exs",
 "test/elixir/map_set_test.exs", "test/elixir/map_test.exs",
 "test/elixir/module/locals_tracker_test.exs",
 "test/elixir/module/types/expr_test.exs",
 "test/elixir/module/types/integration_test.exs",
 "test/elixir/module/types/map_test.exs",
 "test/elixir/module/types/pattern_test.exs",
 "test/elixir/module/types/type_helper.exs",
 "test/elixir/module/types/types_test.exs",
 "test/elixir/module/types/unify_test.exs", "test/elixir/module_test.exs",
 "test/elixir/node_test.exs", "test/elixir/option_parser_test.exs",
 "test/elixir/partition_supervisor_test.exs", "test/elixir/path_test.exs",
 "test/elixir/port_test.exs", "test/elixir/process_test.exs",
 "test/elixir/protocol/consolidation_test.exs", "test/elixir/protocol_test.exs",
 "test/elixir/range_test.exs", "test/elixir/record_test.exs",
 "test/elixir/regex_test.exs", "test/elixir/registry_test.exs",
 "test/elixir/stream_test.exs", "test/elixir/string/chars_test.exs",
 "test/elixir/string_io_test.exs", "test/elixir/string_test.exs",
 "test/elixir/supervisor_test.exs", "test/elixir/system_test.exs",
 "test/elixir/task/supervisor_test.exs", "test/elixir/task_test.exs",
 "test/elixir/test_helper.exs", "test/elixir/tuple_test.exs",
 "test/elixir/typespec_test.exs", "test/elixir/uri_test.exs",
 "test/elixir/version_test.exs"]